config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'
  # get 'posts/index'
  devise_for :users
  root to: 'deshboard#index'
  resources "deshboard"
  resources "users"
  resources "friendships"
  get 'friend_requests', to: 'friendships#friend_request'
  resources "posts"
  resources "likes"
  resources "messages"
  resources "comments"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  scope :ordered, -> { order(created_at: :desc) }
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :commentable, polymorphic: true
	has_many :comments, as: :commentable, dependent: :destroy
	has_many :likes, as: :likeble, dependent: :destroy
	validates_presence_of :content
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :friendship
	has_many :messages, dependent: :destroy
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
  has_one :conversation, dependent: :destroy
  has_many :messages, through: :conversation

end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :likeble, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :conversation
	
	validates_presence_of :content

	after_create_commit { broadcast_append_to "messages" }
end

app/models/post.rb
class Post < ApplicationRecord
	has_one_attached :avatar, dependent: :destroy
	belongs_to :user
	has_many :likes, as: :likeble, dependent: :destroy
	has_many :comments, as: :commentable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_one_attached :avatar, dependent: :destroy
  has_many :friendships, class_name: "Friendship", dependent: :destroy  
  has_many :friends, through: :friendships
  has_many :posts, dependent: :destroy
  has_one :like, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :conversation, through: :friendships

  after_commit :send_mail, on: :create
  

  def send_mail
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource_or_scope)
    UserMailer.login_email(current_user).deliver_now if user_signed_in? if (current_user.current_sign_in_at != current_user.last_sign_in_at )
    signed_in_root_path(resource_or_scope)
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :dob, :country_code, :mob_no, :email, :password, :avatar, :password_confirmation)}

      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :dob, :country_code, :mob_no, :email, :password, :current_password, :avatar, :password_confirmation)}
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		if params[:type] == "Post"
			@commentable = Post.find(params[:id])
		else
			@commentable = Comment.find(params[:id])
		end
		@commentable_type = params[:type]
		@comment = Comment.new
	end

	def create
    @comment = Comment.new(comment_params)
    if comment_params[:commentable_type] == "Post"
			@post = Post.find(comment_params[:commentable_id])
		else
			@current_comment = Comment.find(comment_params[:commentable_id])
		end
		@commentable_type = comment_params[:commentable_type]
		@comment.save
  end

	private
	def comment_params
		params.require(:comment).permit(:content, :user_id, :commentable_id, :commentable_type)
	end
end

app/controllers/deshboard_controller.rb
class DeshboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @posts = Post.ordered
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
		@like = Like.create(user_id: current_user.id, likeble_id: params[:id], likeble_type: params[:type])
		if params[:type] == "Post"
			@post = Post.find(params[:id])
		else
			@post = Comment.find(params[:id])
		end
	end

	def destroy
		@like = Like.find_by(user_id: current_user.id, likeble_id: params[:id], likeble_type: params[:type] )
		@type = params[:type]
		if params[:type] == "Post"
			@post = Post.find(params[:id])
		else
			@post = Comment.find(params[:id])
		end
		@like.destroy
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @friends = Friendship.where(user_id: current_user.id, is_friend: true).ordered
    @friends += Friendship.where(friend_id: current_user.id, is_friend: true).ordered
    @nav_bar = params[:nav_bar]
  end

  def show
    if (Conversation.where(friendship_id: params[:id]).blank?)
      @conversation = Conversation.create(friendship_id: params[:id])
    end
    conversation = Conversation.find_by(friendship_id: params[:id])
    @messages = Message.where(conversation_id: conversation.id)
    @conversation = Conversation.find(conversation.id)
    @friendship = @conversation.friendship
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.save
  end

  private

  def message_params
    params.require(:message).permit(:content, :user_id, :conversation_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
    @comment = Comment.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to root_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  private
    def post_params
      params.require(:post).permit(:content, :type, :user_id, :avatar)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.ordered
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
	FLASH_CLASSES = {
	  notice: 'alert alert-info',
	  success: 'alert alert-success',
	 }.freeze
    
  def flash_class(level)
  	FLASH_CLASSES[level]
  end

  def active(path)
    current_page?(path) ? 'active' : ''
  end

  def full_name(user)
    full_name = user.first_name + " " + user.last_name
  end

  def user_friendship(id)
    @friends = Friendship.where( friend_id: id, is_friend: true)
    @friends += Friendship.where( user_id: id, is_friend: true)
    
    @friends
  end

  def recent_conversation(friends)
  	arrange = []
  	no_chats = []
  	friends.each do |friend|
  		conversation = friend.conversation
  		if conversation.nil?
  			no_chats << friend
  		elsif conversation.messages.blank?
  			no_chats << friend
  		else
	  		message = conversation.messages.last
	  		arrange << message.id
  		end
  	end
  	arrange = arrange.sort_by { |id| -id }
  	recent_chats = []
  	arrange.each do |message_id|
  		message = Message.find(message_id)
  		recent_chats << message.conversation.friendship
  	end
  	no_chats.each do |no_chat|
  		recent_chats << no_chat	
  	end
  	recent_chats
  end

end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
  def comment_time(date)
    time = (Time.now - date)
    if time > 432_000
      date.strftime('%d %B %Y').to_s
    elsif time > 86_400
      days = (((time / 60) / 60) / 24).to_i
      "#{days} day#{'s' if days > 1} ago"
    elsif time > 3600
      hours = ((time / 60) / 60).to_i
      "#{hours} hour#{'s' if hours > 1} ago"
    elsif time > 60
      minutes = (time / 60).to_i
      "#{minutes} minute#{'s' if minutes > 1} ago"
    else
      "#{time.to_i} second ago"
    end
  end
end

app/helpers/deshboard_helper.rb
module DeshboardHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li><ul><li><b><%= full_name(comment.user) %></b></li>
		    <li><%= comment.content %></li>
		    <li style="font-size: 64%;"><%= comment_time(comment.created_at) %></li>
		  	<li><%= render 'likes/like_comment', comment: comment %></li>
		  	<li><%= render 'comments/comment_link', comment: comment %></li></ul>
					<div class="comment_comment_form-<%=comment.id%>" style="align: center;" ></div>
        <ul class="index_comment_comment-<%=comment.id%>">
        	<% if action_name != "show" %>
          	<%= render comment.comments.last(2) %>
          <% else %>
          	<%= render comment.comments %>
          <% end %>
        </ul></li>
<style>
li {
  display:inline;
}

</style>

app/views/comments/_comment_button.html.erb
<%= link_to new_comment_path(id: post.id, type: "Post"), remote: true,  class: "navbar-brand comment-#{post.id}" do %>
  <image src="/assets/comment.png" class="avatar float-left">
  <%= post.comments.count %>
<% end %>

app/views/comments/_comment_link.html.erb
<%= link_to new_comment_path(id: comment.id, type: "Comment"), remote: true,  class: "navbar-brand a comment_comment-#{comment.id}" do %>
  Comment <%= comment.comments.count %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for @comment, remote: true do |f| %>
  <%= f.text_field :content, autocomplete: 'off', id: "text" %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :commentable_id, value: @commentable.id %>
  <%= f.hidden_field :commentable_type, value: @commentable_type %>
  <%= f.submit "Comment", data: { disable_with: false }, class: "btn" %>
<% end %>

app/views/comments/create.js.erb
<% if @commentable_type == "Post" %>
	$(".comment-<%=@post.id%>").html("<%= j render partial: 'comment_button', :locals => {:post => @post} %>");
	$(".show_comment-<%=@post.id%>").append("<%= j render partial: 'comment', :locals => {:comment => @post.comments.last} %>");
	$(".index_comment-<%=@post.id%>").append("<%= j render partial: 'comment', :locals => {:comment => @post.comments.last} %>");
	$(".comment_form-<%=@post.id%>").hide();
	<% if @post.comments.count > 3 %>
		$(".index_comment-<%=@post.id%> li:first").remove();
	<% end %>
<% else %>
	$(".comment_comment-<%=@current_comment.id%>").html("<%= j render partial: 'comment_link', :locals => {:comment => @current_comment} %>");
	$(".show_comment_comment-<%=@current_comment.id%>").append("<%= j render partial: 'comment', :locals => {:comment => @current_comment.comments.last} %>");
	$(".index_comment_comment-<%=@current_comment.id%>").append("<%= j render partial: 'comment', :locals => {:comment => @current_comment.comments.last} %>");
	$(".comment_comment_form-<%=@current_comment.id%>").hide();
	<% if @current_comment.comments.count > 2 %>
		$(".index_comment_comment-<%=@current_comment.id%> li:first").remove();
	<% end %>
<% end %>

app/views/comments/new.js.erb
<% if @commentable_type == "Post" %>
	$(".comment_form-<%=@commentable.id%>").html("<%= j render partial: "form" %>");
	$(".comment_form-<%=@commentable.id%>").show()
<% else %>
	$(".comment_comment_form-<%=@commentable.id%>").html("<%= j render partial: "form" %>");
	$(".comment_comment_form-<%=@commentable.id%>").show()
<% end %>

app/views/likes/_like.html.erb
<% if (post.likes.where(user_id: current_user.id)).blank? %>
  <%= link_to likes_path(id: post.id, type: "Post"), method: :post, class: "navbar-brand post-#{post.id}", remote: true do %>
    <image src="/assets/like.png" class="avatar float-left">
    <%= post.likes.count %>
  <% end %>
<% else %>
  <%= link_to like_path(post.id, type: "Post"), method: :delete, class: "navbar-brand post-#{post.id}", remote: true do %>
    <image src="/assets/unlike.png" class="avatar float-left">
    <%= post.likes.count %>
  <% end %>
<% end %>

app/views/likes/_like_comment.html.erb
<% if (comment.likes.where(user_id: current_user.id)).blank? %>
  <%= link_to likes_path(id: comment.id, type: "Comment"), method: :post, class: "navbar-brand a comment_like-#{comment.id}", remote: true do %>
    Like <%= comment.likes.count %>
  <% end %>
<% else %>
  <%= link_to like_path(comment.id, type: "Comment"), method: :delete, class: "navbar-brand a comment_like-#{comment.id}", remote: true do %>
    Unlike  <%= comment.likes.count %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
<% if @post.likes.last.likeble_type == "Post" %>
	$(".post-<%=@post.id%>").html("<%= j render partial: 'like', :locals => {:post => @post} %>");
<% else %>
	$(".comment_like-<%=@post.id%>").html("<%= j render partial: 'like_comment', :locals => {:comment => @post} %>");
<% end %>

app/views/likes/destroy.js.erb
<% if @type == "Post" %>
	$(".post-<%=@post.id%>").html("<%= j render partial: 'like', :locals => {:post => @post} %>");
<% else %>
	$(".comment_like-<%=@post.id%>").html("<%= j render partial: 'like_comment', :locals => {:comment => @post} %>");
<% end %>

app/views/messages/_form.html.erb
<ul class="navbar-nav table">
  <%= form_for @message do |f| %>
    <li><%= f.text_field :content, class: "form_width", autocomplete: 'off', id: "text" %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :conversation_id, value: @conversation.id %>
        <%= f.submit "Send Message", data: { disable_with: false }, class: "btn btn-primary", id: "tester" %></li>
  <% end %>
</ul>

app/views/messages/_friends_list.html.erb
<% if (friend.user_id == current_user.id) %>
  <% user = User.find(friend.friend_id) %>
<% else %>
  <% user = User.find(friend.user_id) %>
<% end %>
  
<th><%= link_to user_path(user), class: "link_to", remote: true do %>
      <%= render "users/profile_avatar", user: user %>
    <% end %></th>
<td>
  <ul class="navbar-nav mr-auto float-right">
    <li class="nav-item">
      <%= link_to 'Message', message_path(friend), remote: true, class: 'btn btn-primary' %>
    </li>
  </ul>
</td>
   

app/views/messages/_message.html.erb
<div class="cont-<%= message.user.id %>">
  <div class="message-box msg-<%= message.user.id %> " >
    <h6 class="name"> <%= message.content %> </h6>
      <li class="nav-item" style="font-size: 50%; text-align: right;">
        <%= message.created_at %>
      </li>
  </div>
</div>

app/views/messages/_show.html.erb
<span class="close">&times;</span>
<%= turbo_include_tags %>
<% if (@friendship.user_id == current_user.id) %>
  <% friend = User.find(@friendship.friend_id) %>
<% else %>
  <% friend = User.find(@friendship.user_id) %>
<% end %>
  <div class="friend_name">
    <h5 class='float-left'><%= render "users/profile_avatar", user: friend %></h5>
  </div>
<div class='clearfix'></div>
<hr>
<%= turbo_stream_from "messages" %>
<div class="div_height divScroll" id="messages" >
  <ul class="navbar-nav">
    <%= render @messages %>
  </ul>
</div> 

<%= render "form" %>

<script>
  var modal = document.getElementById("myModal");
  var span = document.getElementsByClassName("close")[0];
  span.onclick = function() {
    modal.style.display = "none";
    document.location.reload(true)
  }
  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
      document.location.reload(true)
    }
  }
</script>

app/views/messages/index.html.erb
<% if @nav_bar == "true" %> 
  <%= render 'layouts/nav', user: current_user %> 
  <div class='clearfix'></div><hr>
<% end %>
<div class="row" >
  <div class="col-md-6">
    <div class="show_post">
      <div class="show_post">
        <div class="card">
          <table class="table">
            <tbody>
            <tr><h6 align="center">Recent chats </h6></tr><hr/>
              <% recent_conversation(@friends).each do |friend| %>
                <tr>
                  <% if (!(friend.conversation).blank?) %>
                    <%= render 'friends_list', friend: friend %>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
          <table class="table">
            <tbody>
            <tr><h6 align="center"> Friends </h6></tr><hr/>
              <% @friends.each do |friend| %>
                <tr>
                  <% if ((friend.conversation).blank?) %>
                    <%= render 'friends_list', friend: friend %>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
        </div><hr>
      </div> 
    </div>
  </div>
</div>

app/views/messages/show.html.erb
<%= render partial: 'show' %>

app/views/messages/show.js.erb
$(".modal-content").html("<%= j render partial: "show" %>");
$("#myModal").show();

app/views/posts/_index.html.erb
<% if current_user != @user %>
  <span class="close">&times;</span>
<% end %>
<%= render 'layouts/nav', user: @user %>
<div class='clearfix'></div>
<hr/>
<div class="row scroll" >
  <div class="col-md-6">
    <div class="card" style="width: 540px;">
			<%= render "posts", posts: @posts %>
		</div>
  </div>
</div>
<script>
  var modal = document.getElementById("myModal");
  var span = document.getElementsByClassName("close")[0];
  span.onclick = function() {
    modal.style.display = "none";
  }
  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    }
  }
</script>

app/views/posts/_post.html.erb
<tr>
  <th><%= link_to user_path(post.user), class: "link_to", remote: (current_user != post.user) do %>
    <%= render "users/profile_avatar", user: post.user %>
    <% end %>
    <p style="font-size: small;"><%= post.created_at %></p></th>
</tr>
<tr>
  <td><%= post.content %></td>
</tr>
<tr>
  <% if post.avatar.attached? %>
    <td><img src="<%=(url_for(post.avatar))%>" class="float-left"></td>
  <% end %>
</tr>

app/views/posts/_posts.html.erb
<div class="show_post">
  <% posts.each do |post| %>
    <div class="card">
      <table class="table">
        <tbody>
          <%= render "posts/post", post: post %>
          <tr>
            <td><div class="panel-body text-center">
                  <ul class="nav nav-pills float-right">
                    <li class="nav-item" >
                      <%= render 'likes/like', post: post %>
                      <%= render 'comments/comment_button', post: post %>
                      <% if current_user == @user %>
                        <%= link_to 'Show Post', post_path(post) %>
                      <% end %>
                    </li>
                  </ul>
                 </div>
            </td>
          </tr>
          <tr><td>
            <div class="comment_form-<%=post.id%>" style="align: center;" ></div>
            <ul class="index_comment-<%=post.id%>">
              <%= render post.comments.last(3) %>
            </ul>
          </td></tr>
        </tbody>
      </table>
    </div><hr>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= render 'index' %>

app/views/posts/index.js.erb
$(".modal-content").html("<%= j render partial: "index" %>");
$("#myModal").show();

app/views/posts/new.html.erb
<div class='clearfix'></div>
<div class="row" >
  <div class="col-md-6">
    <div class="card">
      <div class="show_post">
        <div class="card">
          <%= form_for @post do |f| %>
            <table class="table">
              <tbody>
                <div class="row">
                  <div class="col-md-8">
                    <% if @post.errors.any? %>
                      <div id="error_explanation">
                        <h2>
                         <%= pluralize(@post.errors.count, "error") %>
                         prohibited this post from being saved:</h2>
                        <ul>
                        <% @post.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>
                    <tr>
                      <td><div class="form-group">
                        <b><%= f.label :content, class: "control-label" %></b>
                        <%= f.text_area :content, class: "form-control" %>
                      </div></td>
                    </tr>
                    <tr>
                      <td><div class="form-group">
                        <b><%= f.label :image, class: "control-label" %></b>
                        <%= f.file_field :avatar, class: "form-control" %>
                      </div></td>
                    </tr>
                    <div class="form-group">
                      <%= f.hidden_field :user_id, value: current_user.id %>
                      <%= f.hidden_field :is_post, value: true %>
                    </div>
                  </div>
                </div>
              </tbody>
            </table>
            <table class="table">
              <tbody>
                  <tr>
                    <td><div class="panel-body text-center">
                          <%= link_to 'Back', :back, class: 'btn btn-primary' %>
                          <%= f.submit "Create Post", class: "btn btn-primary" %>
                        </div></td>
                  </tr>
              </tbody>
            </table>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class='clearfix'></div>
<div class="row" >
  <div class="col-md-6">
    <div class="card">
			<div class="show_post">
				<div class="card">
					<table class="table">
						<tbody>
						  <%= render "posts/post", post: @post %>
						  <tr>
		            <td><div class="panel-body text-center">
		                  <ul class="nav nav-pills float-right">
		                    <li class="nav-item" >
		                      <%= render 'likes/like', post: @post %>
		                      <%= render 'comments/comment_button', post: @post %>
		                      <%= link_to 'Back', :back %>
		                    </li>
		                  </ul>
		                 </div>
		            </td>
		          </tr>
		          <tr><td>
		            <div class="comment_form-<%=@post.id%>" style="align: center;" ></div>
		            <ul class="show_comment-<%=@post.id%>">
		            	<%= render @post.comments %>
		            </ul>
		          </td></tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/_profile_avatar.html.erb
<% if user.avatar.attached? %>
  <img src="<%=(url_for(user.avatar))%>" class="avatar float-left">
<% else %>
  <img src="/assets/avatar.png" class="avatar float-left">
<% end %>
<%= full_name(user) %> 

app/views/users/_show.html.erb
<% if current_user != @user %>
  <span class="close">&times;</span>
<% end %>
<%= render 'layouts/nav', user: @user %>
<div class='clearfix'></div>
<hr>

<div class="row scroll" >
  <div class="col-md-6">
    <div class="show_post">
      <div class="card">
        <div class="card-header">
          Profile
          <div class="float-right">
            <%= (link_to 'Edit Profile', edit_user_registration_path(@user)) if current_user.id == @user.id %>
          </div>
        </div>
        <table class="table table-bordered mb-0">
          <tbody>
              <tr>
                <th> Name </th>
                <td><%= full_name(@user) %></td>
              </tr>
              <tr>
                <th> Email </th>
                <td><%= @user.email %></td>
              </tr>
              <tr>
                <th> Date Of Birth </th>
                <td><%= @user.dob.strftime("%d %B %Y") %></td>
              </tr>
              <tr>
                <th> Mobile No. </th>
                <td><%= @user.country_code %> <%= @user.mob_no %></td>
              </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<script>
  var modal = document.getElementById("myModal");
  var span = document.getElementsByClassName("close")[0];
  span.onclick = function() {
    modal.style.display = "none";
  }
  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    }
  }
</script>

app/views/users/_user_button.html.erb
<% user = (Friendship.where( user_id: current_user.id, friend_id: find_friend.id)) %>
<% friend = (Friendship.where( user_id: find_friend.id, friend_id: current_user.id)) %>
<% friend = user + friend %>
<% if friend.blank? %>
  <%= link_to 'Add Friend', friendships_path(friend_id: find_friend.id), method: :post, remote: true, class: 'btn btn-primary', style: "width: 230px;" %>
<% elsif !(friend[0].is_friend) %>
  <% if user.blank? %>
    <%= link_to 'Accept', friendship_path(friend[0].id),method: :put, remote: true, class: 'btn btn-success', style: "width: 115px;" %>
    <%= link_to 'Cancel', friendship_path(find_friend.id), method: :delete, remote: true, class: 'btn btn-danger', style: "width: 115px;" %>
  <% else %>
    <%= link_to 'Cancel Request', friendship_path(find_friend.id), method: :delete, remote: true, class: 'btn btn-danger', style: "width: 230px;" %>
  <% end %>
<% else %>
  <%= link_to 'Message', message_path(friend[0]), remote: true, class: 'btn btn-primary', style: "width: 115px;" %>
  <%= link_to 'Remove', friendship_path(find_friend.id), method: :delete, remote: true, class: 'btn btn-danger', style: "width: 115px;" %>
<% end %>

app/views/users/create.js.erb
$("#user-li-<%= find_frind.id %>").html("<%= j render partial: "user_button", :locals => {:find_friend => find_friend} %>");

app/views/users/index.html.erb
<div class='clearfix'></div>
<div class="row" >
  <div class="col-md-6">
    <div class="show_post">
      <div class="show_post">
        <div class="card">
          <table class="table">
            <% @users.each do |find_friend| %>
              <% if (current_user.id != find_friend.id) %>
                <tbody>
                  <tr>
                    <th><%= link_to user_path(find_friend), class: "link_to", remote: (find_friend != current_user) do %>
                          <%= render "profile_avatar", user: find_friend %>
                        <% end %>      
                          </th>
                    <td><ul class="navbar-nav mr-auto">
                          <li class="nav-item user-li-<%= find_friend.id %>" style="text-align: center;">
                            <%= render "user_button" , find_friend: find_friend %>
												  </li>
                        </ul></td>
                  </tr>
                </tbody>
              <% end %>
            <% end %>
          </table>
        </div>
      </div> 
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'show' %>

app/views/users/show.js.erb
$(".modal-content").html("<%= j render partial: "show" %>");
$("#myModal").show();