config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'
  # get 'posts/index'
  devise_for :users
  root to: 'deshboard#index'
  resources "deshboard"
  resources "users"
  resources "friendships"
  get 'friend_requests', to: 'friendships#friend_request'
  resources "posts"
  resources "likes"
  resources "messages"
  resources "comments"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  scope :ordered, -> { order(created_at: :desc) }
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :commentable, polymorphic: true
	has_many :comments, as: :commentable, dependent: :destroy
	has_many :likes, as: :likeble, dependent: :destroy
	validates_presence_of :content
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :friendship
	has_many :messages, dependent: :destroy
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
  has_one :conversation, dependent: :destroy
  has_many :messages, through: :conversation

end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :likeble, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :conversation
	
	validates_presence_of :content

	after_create_commit { broadcast_append_to "messages" }
end

app/models/post.rb
class Post < ApplicationRecord
	has_one_attached :avatar, dependent: :destroy
	belongs_to :user
	has_many :likes, as: :likeble, dependent: :destroy
	has_many :comments, as: :commentable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_one_attached :avatar, dependent: :destroy
  has_many :friendships, class_name: "Friendship", dependent: :destroy  
  has_many :friends, through: :friendships
  has_many :posts, dependent: :destroy
  has_one :like, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :conversation, through: :friendships

  after_commit :send_mail, on: :create
  

  def send_mail
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		if params[:type] == "Post"
			@commentable = Post.find(params[:id])
		else
			@commentable = Comment.find(params[:id])
		end
		@commentable_type = params[:type]
		@comment = Comment.new
	end

	def create
    @comment = Comment.new(comment_params)
    if comment_params[:commentable_type] == "Post"
			@post = Post.find(comment_params[:commentable_id])
		else
			@current_comment = Comment.find(comment_params[:commentable_id])
		end
		@commentable_type = comment_params[:commentable_type]
		@comment.save
  end

	private
	def comment_params
		params.require(:comment).permit(:content, :user_id, :commentable_id, :commentable_type)
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
		@like = Like.create(user_id: current_user.id, likeble_id: params[:id], likeble_type: params[:type])
		if params[:type] == "Post"
			@post = Post.find(params[:id])
		else
			@post = Comment.find(params[:id])
		end
	end

	def destroy
		@like = Like.find_by(user_id: current_user.id, likeble_id: params[:id], likeble_type: params[:type] )
		@type = params[:type]
		if params[:type] == "Post"
			@post = Post.find(params[:id])
		else
			@post = Comment.find(params[:id])
		end
		@like.destroy
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
    @comment = Comment.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to root_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  private
    def post_params
      params.require(:post).permit(:content, :type, :user_id, :avatar)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.ordered
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
	FLASH_CLASSES = {
	  notice: 'alert alert-info',
	  success: 'alert alert-success',
	 }.freeze
    
  def flash_class(level)
  	FLASH_CLASSES[level]
  end

  def active(path)
    current_page?(path) ? 'active' : ''
  end

  def full_name(user)
    full_name = user.first_name + " " + user.last_name
  end

  def user_friendship(id)
    @friends = Friendship.where( friend_id: id, is_friend: true)
    @friends += Friendship.where( user_id: id, is_friend: true)
    
    @friends
  end

  def recent_conversation(friends)
  	arrange = []
  	no_chats = []
  	friends.each do |friend|
  		conversation = friend.conversation
  		if conversation.nil?
  			no_chats << friend
  		elsif conversation.messages.blank?
  			no_chats << friend
  		else
	  		message = conversation.messages.last
	  		arrange << message.id
  		end
  	end
  	arrange = arrange.sort_by { |id| -id }
  	recent_chats = []
  	arrange.each do |message_id|
  		message = Message.find(message_id)
  		recent_chats << message.conversation.friendship
  	end
  	no_chats.each do |no_chat|
  		recent_chats << no_chat	
  	end
  	recent_chats
  end

end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
  def comment_time(date)
    time = (Time.now - date)
    if time > 432_000
      date.strftime('%d %B %Y').to_s
    elsif time > 86_400
      days = (((time / 60) / 60) / 24).to_i
      "#{days} day#{'s' if days > 1} ago"
    elsif time > 3600
      hours = ((time / 60) / 60).to_i
      "#{hours} hour#{'s' if hours > 1} ago"
    elsif time > 60
      minutes = (time / 60).to_i
      "#{minutes} minute#{'s' if minutes > 1} ago"
    else
      "#{time.to_i} second ago"
    end
  end
end

app/helpers/deshboard_helper.rb
module DeshboardHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<h2 class='float-left'>
<%= render "users/profile_avatar", user: user %></h2>
<ul class="nav nav-pills float-right">
  <li class="nav-item <%= active(users_path) %>" >
  <%= link_to user_path(user), class: "link_to", remote: (user != current_user),
          class: "nav-link #{users_path}" do %>
     Profile
       <% end %>
  </li>
  <% if (user.id == current_user.id) %>
    <li class="nav-item <%= active(messages_path) %>">
      <%= link_to 'Messages', messages_path(nav_bar: true), class: "nav-link" %>
    </li>
  <% end %>
  <li class="nav-item <%= active(friendships_path) %>">
    <%= link_to friendships_path(:user_id => user.id), remote: (user != current_user), class: "nav-link #{friendships_path}" do %>
      Friends (<%= user_friendship(user.id).count %>)
     <% end %>
  </li>
  <li class="nav-item <%= active(posts_path) %>">
  <%= link_to posts_path(:user_id => user.id), remote: (user != current_user), class: "nav-link" do %>
     Posts (<%= user.posts.count %>)
   <% end %>
  </li>
</ul>
<style type="text/css">
  .div-<%= user.id == current_user.id %> {
    background-color: white;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light
            navbar-inverse navbar-fixed-top mb-4">
      <%= link_to root_path, class: 'navbar-brand' do %>
        <% if current_user %>
          <image src="/assets/home.png" class="avatar float-left">
        <% end %>
      <% end %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <% if current_user %>
            <%= link_to users_path, class: 'nav-link' do %>
              <image src="/assets/find_friend.png" class="avatar float-left">
            <% end %>
          <% end %>
        </li>
        <li class="nav-item <%= root_path %>">
          <% if current_user %>
            <%= link_to new_post_path, class: "nav-link" do %>
              <image src="/assets/new_post.png" class="avatar float-left">
            <% end %>
          <% end %>
        </li>
      </ul>
      <div class="pull-right">
        <ul class="navbar-nav">
          <% if current_user %>
            <% request_count = Friendship.where(friend_id: current_user.id, is_friend: false).count %>
            <li class="nav-item">
              <%= link_to friend_requests_path, class: "nav-link" do %>
                <div><image src="/assets/friend_request.png" class="avatar float-left"> <span style="margin: 0px -3px 0px -11px; color: red;"><%= request_count %></span></div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to messages_path(nav_bar: false), class: "nav-link" do %>
                <div><image src="/assets/messages.png" class="avatar float-left"></div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_path(current_user), class: "nav-link" do %>
                <image src="/assets/my_account.png" class="avatar float-left"> 
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
                <image src="/assets/log_out.png" class="avatar float-left"> 
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class='container' role='main'>
    <% flash.each do |key, value| %>
      <!-- <div class="<%#= flash_class(key.to_sym) %> show" ><%#= value %></div> -->
    <% end %>

    <%= yield %>
  </div>
  <div id="myModal" class="modal">
  <div class="modal-content div-false">
    <div class="popuptext" id="myPopup"></div>
  </div>
</div>
  </body>
</html>
<style>
  <%= ".msg-#{current_user&.id}" %> {
  background-color: #555555 !important;
  padding: 10px;
  }
  <%= ".cont-#{current_user&.id}" %> {
  display: flex;
  justify-content: flex-end
  }
  .message-box {
  width: fit-content;
  max-width: 50%;
  padding: 5px;
  border-radius: 10px;
  margin-bottom: 10px;
  background-color: #007bff ;
  padding: 10px
}
</style>